//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Engine.rc
//
#define ID_AUD_HELP                     3
#define ID_VST_HELP                     3
#define ID_ASIO_SETUP                   4
#define ID_CLEAR_REGISTRATION           6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SYNTHETYPE                  129
#define IDS_CANT_NEST_PAGED_PANEL       129
#define IDD_NEWUG                       130
#define IDS_MN_ENUM_TO_BOOLS            130
#define IDS_MG_SUB_CONTROLS_OLD         131
#define IDS_MN_FLOAT_TO_BOOL            132
#define IDI_CONTAINER_ICON              133
#define IDS_MN_BOOLS_TO_LIST            133
#define IDD_OPTIONS                     134
#define IDS_MN_SYSTEM_COMMAND2          134
#define IDD_REGISTRATION                135
#define IDS_MN_INT_TO_LIST              135
#define IDS_MN_IMAGE_FRAME              136
#define IDS_MG_SPECIAL_FEEDBACK         137
#define IDD_DOC_PROP                    138
#define IDS_MN_PATCH_MEM_TEXT_IN        138
#define IDI_MUTE                        139
#define IDS_MN_PATCH_MEM_LIST_IN        139
#define IDI_VST                         140
#define IDS_MN_PATCH_MEM_FLOAT_IN2      140
#define IDI_MUTE1                       141
#define IDI_LOCKED                      141
#define IDS_FLOAT_TO_VOLTS              141
#define IDS_VOLTS_TO_FLOAT              142
#define IDS_HOST_PATCH_COMMANDS         143
#define IDD_DEBUG_OPT                   144
#define IDS_MN_IMAGE2                   144
#define IDS_MG_OLD                      144
#define IDS_MN_FLOAT_SCALER             145
#define IDS_MN_PP_SETTER                146
#define IDD_PATCH_MGR                   147
#define IDS_MN_ANIMATION_SCALER_DB      147
#define IDS_MN_RANDOM                   148
#define IDS_AUTOMATOR_WITHOUT_PATCH_SELECT 149
#define ID_VIEW_PROPERTIESWND           150
#define IDS_MG_DIAGNOSTIC               150
#define IDS_MN_DEFAULT_SETTER           151
#define IDS_MN_VOICE_SPLITTER           152
#define IDS_MN_PP_WATCHER               153
#define IDS_MN_INT_TEXT_TO_ENUM         154
#define IDS_MN_FLOAT_ADDER2             155
#define IDS_VOLTS_TO_FLOAT2             156
#define IDD_SAVE_VST                    162
#define IDD_CONNECT_UG                  163
#define IDD_VST_ABOUT                   164
#define IDB_ZOOM                        166
#define IDD_SELECT_MODULE               167
#define IDI_SEM                         168
#define IDB_BROWSE_BTNU                 171
#define IDD_DIALOG1                     171
#define IDB_BROWSE_BTND                 172
#define IDD_SAVE_VST2                   177
#define ID_HELP_ONLINEADVICE            181
#define IDD_USER_SETTINGS               181
#define IDB_BITMAP1                     182
#define IDB_IMAGE_NOT_FOUND             182
#define IDD_FILE_PATHS                  182
#define ID_HELP_ONLINENEWS              183
#define IDD_REGISTRATION2               183
#define ID_HELP_GETREGISTEREDONLINE     184
#define IDS_MN_INCREMENT2               191
#define IDR_BLOB1                       192
#define IDR_BLOB2                       193
#define IDS_MN_PATCH_MEM_LIST_IN_B      196
#define IDD_ASSIGN_CONTROLLER           197
#define IDR_MANIFEST                    200
#define IDS_MN_ENUM_TO_INT_TEXT         201
#define IDD_SKELETON_CODE               202
#define IDR_MAINFRAME_256               205
#define IDS_MG_FLOW_CONTROL             239
#define IDS_MG_MIDI                     292
#define IDS_MG_CONVERSION               299
#define IDS_MG_FILTERS                  301
#define IDS_MG_MODIFIERS                303
#define IDS_MG_MATH                     312
#define IDS_MG_EFFECTS                  317
#define IDS_MG_INPUT_OUTPUT             323
#define IDS_MG_SPECIAL                  324
#define IDS_MG_LOGIC                    325
#define IDS_MN_NOR_GATE                 357
#define IDS_MN_AUDIO_OUT                401
#define IDS_MN_ADSR                     402
#define IDS_MN_CONTAINER                403
#define IDS_MN_IO_MOD                   404
#define IDS_MN_SLIDER                   405
#define IDS_MN_TEXT_ENTRY               406
#define IDS_MN_LIST_ENTRY               407
#define IDS_MN_MIDI_TO_CV               409
#define IDS_MN_LEVEL_ADJ                411
#define IDS_MN_SV_FILTER                412
#define IDS_MN_VCA                      413
#define IDS_MN_DRUM_TRIGGER             414
#define IDS_MN_PATCH_SELECT             415
#define IDS_MN_MIDI_IN                  416
#define IDS_MN_DELAY                    417
#define IDS_MN_CLIPPER                  419
#define IDS_MN_MONITOR                  420
#define IDS_MN_THRASHER                 422
#define IDS_MN_AUDIO_IN                 429
#define IDS_MN_MIDI_OUT                 430
#define IDS_MN_CONTROLLERS              431
#define IDS_MN_PANEL_GROUP              435
#define IDS_MN_PAN                      437
#define IDS_MN_SWITCH_1_MANY            438
#define IDS_MN_SWITCH_MANY_1            439
#define IDS_MN_VST_PLUGIN               440
#define IDS_MN_PEAK_FOLLOWER            441
#define IDS_MN_X_MIX                    442
#define IDS_MN_STEP_SEQUENCER           444
#define IDS_MN_DRUM_SEQUENCER           446
#define IDS_MN_WAVESHAPER               447
#define IDS_MN_MOOG_FILTER              448
#define IDS_MN_LED_INDICATOR            449
#define IDS_MN_8_STAGE_ENV              450
#define IDS_MN_RECTIFIER                451
#define IDS_MN_AND_GATE                 452
#define IDS_MN_OR_GATE                  453
#define IDS_MN_XOR_GATE                 454
#define IDS_MN_NAND_GATE                455
#define IDS_MN_NOT_GATE                 456
#define IDS_MN_1_POLE_LP                458
#define IDS_MN_FREQ_RESPONSE_TEST       459
#define IDS_MN_PEAK_METER               460
#define IDS_MN_RING_MODULATOR           461
#define IDS_MN_FIXED_VALUES             462
#define IDS_MN_SCOPE                    463
#define IDS_MN_KEYBOARD                 464
#define IDS_MN_SAMPLE_AND_HOLD          465
#define IDS_MN_ALL_PASS                 467
#define IDS_MN_FREQ_ANALYSER            468
#define IDS_MN_UNNAMED                  474
#define IDS_MN_TESTER                   475
#define IDS_MN_WAVESHAPER2              476
#define IDS_MN_1_KHZ_TONE               480
#define IDS_MN_MIDI_RECORDER            481
#define IDS_MN_BINARY_COUNTER           482
#define IDS_MN_DECADE_COUNTER           483
#define IDS_MN_TRIGGER_TO_MIDI          484
#define IDS_MN_SHIFT_REGISTER           485
#define IDS_MN_VOLTAGE_TO_LIST2         487
#define IDS_MN_MONOSTABLE               489
#define IDS_MN_MIDI_AUTOMATOR           490
#define IDS_MN_MIDI_AUTOMATOR_OUTPUT    491
#define IDS_MN_MIDI_FILTER              492
#define IDS_MN_STEP_COUNTER             493
#define IDS_MN_VST_INPUT                494
#define IDS_MN_VST_OUTPUT               495
#define IDS_MN_MULTISTAGE_ENV           496
#define IDS_MN_COMPARATOR               498
#define IDS_MN_VOLTAGE_TO_LIST          499
#define IDS_MN_VOLT_METER               500
#define IDS_MN_1_POLE_HP                501
#define IDS_MN_QUANTISER                503
#define IDS_MN_DENORMAL_CLEANER         504
#define IDS_MN_DENORMAL_DETECTOR        505
#define IDS_MN_MULTIPLY                 506
#define IDS_MN_DIVIDE                   507
#define IDS_MN_SUBTRACT                 508
#define IDS_MN_PARAMETRIC_EQ            509
#define IDS_MN_OS_COMMAND               510
#define IDS_MN_FLOOR                    511
#define IDS_MN_CEIL                     512
#define IDS_MN_SOUND_OUT                515
#define IDS_MN_SOUND_IN                 516
#define IDS_MN_DELAY2                   517
#define IDS_MN_VOICE_COMBINER           518
#define IDS_MN_WAVE_PLAYER              522
#define IDS_MN_WAVE_RECORDER            523
#define IDS_MN_FEEDBACK_DELAY           524
#define IDS_MN_STEP_COUNTER2            525
#define IDC_SRATE                       1011
#define IDC_AUDIO_OUT                   1012
#define IDC_PATCH_COUNT                 1019
#define IDC_MIDI_OUT                    1020
#define IDC_MIDI_IN                     1021
#define IDC_LATENCY                     1022
#define IDC_COMMENTS                    1023
#define IDC_COMMENT                     1024
#define IDC_MIDI_FILES                  1025
#define IDC_AUDIO_FILES                 1026
#define IDC_MIDI_BUT                    1027
#define IDC_AUDIO_BUT                   1028
#define IDC_VERSION_MAJ                 1028
#define IDC_VERSION_MIN                 1029
#define IDC_SPIN1                       1029
#define IDC_VST_FILES                   1029
#define IDC_SPIN2                       1030
#define IDC_VST_BUT                     1030
#define IDC_SEM_FILES                   1031
#define IDC_NOTE_SUSPEND                1032
#define IDC_SEM_BUT                     1032
#define IDC_TRACE_EVNT                  1033
#define IDC_TO_PATCH_LO                 1034
#define IDC_TRACE_POLY                  1034
#define IDC_TO_PATCH_HI                 1035
#define IDC_TRACE_STAT                  1035
#define IDC_COPY                        1036
#define IDC_TRACE_FUNC                  1036
#define IDC_BROWSE                      1037
#define IDC_DBG_BLK_SIZE                1037
#define IDC_BROWSE_BT                   1038
#define IDC_DBG_BLK_CHECK               1038
#define IDC_LOAD_LAST                   1039
#define IDC_DBG_DS_EXCLUSIVE            1039
#define IDC_AUTO_PLAY                   1040
#define IDC_LABEL_FONT                  1040
#define IDC_OUTPUT_VALUE_CHECK          1040
#define IDC_UNDO_ENABLED                1040
#define IDC_AUTO_RELOAD                 1041
#define IDC_LABEL_FONT_NAME             1042
#define IDC_GRAPHICS_QUALITY            1042
#define IDC_INHIBIT_WAVE_ERRORS         1043
#define IDC_EDIT1                       1044
#define IDC_FILENAME                    1044
#define IDC_HELP_TEXT                   1044
#define IDC_REGISTRATION_KEY            1044
#define IDC_CC_NUMBER                   1044
#define IDC_CLASSNAME                   1044
#define IDC_TRACE_TIME_TO               1045
#define IDC_4CHARCODE                   1045
#define IDC_HELP_TEXT2                  1045
#define IDC_SERIAL                      1045
#define IDC_TRACE_TIME_FROM             1046
#define IDC_AUTHOR                      1046
#define IDC_PRODUCT                     1046
#define IDC_CPU_LOAD                    1047
#define IDC_LOW_LATENCY                 1048
#define IDC_ABOUT                       1048
#define IDC_LATENCY_READOUT             1050
#define IDC_UNREGISTERED                1051
#define IDC_TO_UG                       1052
#define IDC_MONO_USE_OK                 1052
#define IDC_TO_PLUG                     1053
#define IDC_IS_SYNTH                    1053
#define IDC_FROM_PLUG                   1054
#define IDC_STEREO                      1054
#define IDC_MOD_LIST                    1056
#define IDC_VERSION                     1057
#define IDC_LIST1                       1061
#define IDC_REMOVE                      1062
#define IDC_ADD                         1063
#define IDC_LATENCY_CAPTION             1063
#define IDC_LATENCY_CAPTION2            1064
#define IDC_DX_SAMPLE_RATE_CAPTION      1065
#define IDC_REGISTERED_TO               1070
#define IDC_BUTTON1                     1071
#define IDC_BUTTON2                     1072
#define IDC_TYPE_RPN                    1073
#define IDC_TYPE_CC2                    1074
#define IDC_SERIAL_LABEL                1074
#define IDC_TYPE_NRPN                   1075
#define IDC_SYSEX_EDIT                  1075
#define IDC_LIST2                       1076
#define IDC_REGO_NAME_LABLE             1077
#define ID_UPLEVEL                      32774
#define ID_BUTTONPLAY                   32776
#define ID_HELP_CONT                    32777
#define ID_BUTTON_STOP                  32779
#define ID_HELP_AB                      32781
#define ID_VIEW_CONTROLS                32783
#define ID_DEBUG_FUNC_LIST              32785
#define ID_DEBUG_OPTIONS                32786
#define ID_VIEW_OPTIONS                 32787
#define ID_PATCH_MGR                    32788
#define ID_INS_PREFAB                   32789
#define ID_DELETE_MODULE                32790
#define ID_LOCK_MODULE                  32791
#define ID_EDIT_MODE                    32792
#define ID_EDIT_SNAP                    32793
#define ID_EDIT_DELETE                  32794
#define ID_EDIT_CONTAIN                 32795
#define ID_EDIT_DEL_KEY                 32796
#define ID_EDIT_CUT_KEY                 32797
#define ID_EDIT_COPY_KEY                32798
#define ID_EDIT_PASTE_KEY               32799
#define ID_DEBUG_SELF_DOC               32800
#define ID_OPEN_COMMENT                 32801
#define ID_DEBUG_SELF_DOC2              32802
#define ID_EDIT_UNCONTAIN               32803
#define ID_PLACEHOLDER                  32805
#define IDS_LANG_DLL_ERROR              32806
#define IDS_DELETE                      32808
#define IDS_PASTE                       32809
#define IDS_CUT                         32810
#define IDS_CONTAIN                     32811
#define IDS_INSERT_UG                   32812
#define IDS_NEW_LINE                    32813
#define IDS_OPEN_WINDOW                 32814
#define IDS_CLOSE_WINDOW                32815
#define IDS_INSERT_PREFAB               32816
#define ID_HTML_HELP                    32818
#define IDS_OSCILLATOR                  32819
#define IDS_WAVEFORM                    32820
#define IDS_ADSR                        32821
#define IDS_PDOSCILLATOR                32822
#define IDS_8_STAGE                     32823
#define IDS_MULTISTAGE_ENV              32824
#define IDS_MN_IMAGE                    32826
#define IDS_MG_CONTROLS                 32828
#define IDS_MG_DEBUG                    32829
#define IDS_MN_SCALER                   32830
#define IDS_MN_PARAM_FLOAT_IN           32831
#define IDS_MG_CONTROL_WIDGET           32832
#define IDS_MN_PARAM_FLOAT_OUT          32833
#define IDS_MN_SPRING                   32835
#define IDS_MN_PARAM_ENUM_IN            32836
#define IDS_MN_INCREMENT                32837
#define IDS_MN_TEXT                     32838
#define IDS_MN_LIST_ENTRY2              32839
#define IDS_MN_PAGED_GROUP              32840
#define IDS_MN_TEXT_TO_FLOAT            32841
#define IDS_MN_FLOATS_TO_ENUM           32842
#define ID_VST_FILE_LOAD_BANK           34909
#define ID_VST_FILE_SAVE_BANK           34910
#define ID_VST_FILE_LOAD_INST           34911
#define ID_VST_FILE_SAVE_INST           34912
#define POPUP_MENU_CONNECT              34913
#define ID_SELF_TEST                    34914
#define POPUP_MENU_STRUCTURE            34915
#define POPUP_MENU_PROPERTIES           34916
#define POPUP_MENU_CONTROLS             34917
#define POPUP_MENU_MUTE                 34918
#define POPUP_MENU_PASTE                34919
#define POPUP_MENU_DEBUG_TOGGLE         34920
#define POPUP_MENU_UG_HELP              34921
#define POPUP_MENU_TOGGLE_RACKMODULE    34922
#define POPUP_MENU_ABOUT                34923
#define POPUP_MENU_TOGGLE_LOCKED        34924
#define POPUP_MENU_REPLACE              34925
#define POPUP_MENU_SCREENSHOT           34926
#define ID_VST_PROG_CHANGE              34927
#define ID_VST_PROG_CHANGE_RANGE        35055
#define POPUP_MENU_DEBUG_CODE           35056
#define POPUP_MENU_NODE_DELETE          35057
#define POPUP_MENU_NODE_INSERT          35058
#define POPUP_MENU_NODE_SUSTAIN         35059
#define POPUP_MENU_VST_EDIT_NON_GUI     35060
#define POPUP_MENU_STRUCTURE_WPF        35061
#define POPUP_MENU_DELETE_BYPASS        35064
#define ID_CHANGE_SKIN                  35128
#define ID_CHANGE_SKIN_RANGE            35178
#define ID_VIEW_LANGUAGE                35179
#define ID_TOGGLE_RUN                   35283
#define ID_HELP_INJECTDEBUGVST          35285
#define ID_HELP_INJECTDEBUGVST2         35286
#define ID_HELP_SCANMODULES             35287
#define ID_EDIT_SELECT_NEXT             35289
#define ID_EDIT_SELECT                  35290
#define ID_ENABLE_UNDO                  35291
#define ID_EDIT_PREFERANCES             35294
#define ID_SCREENSHOT                   35297
#define ID_EDIT_MOVEFRONT               35298
#define ID_EDIT_MOVEBACK                35299
#define POPUP_MENU_USER_DEF             41301
#define POPUP_MENU_USER_DEF_RANGE       44300

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         35313
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
